### ISSUE TITLE
trtpy   RuntimeError: Can not get real name from key[sxaivip

### ISSUE THREAD

**Issue by QIANXUNZDL123** [shouxieai/tensorRT_Pro#107]
我之前设置了trtpy set-key sxaivip  安装了trt get-env 之后在查看就报错，请问该怎么设置

Download failed: http://zifuture.com:1556/fs/sxaivip
.txt
Traceback (most recent call last):
  File "/root/miniconda3/envs/TensorRT/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/miniconda3/envs/TensorRT/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/TensorRT/lib/python3.7/site-packages/trtpy/__main__.py", line 834, in <module>
    sys.exit(cmd_funcs[args.cmd](args))
  File "/root/miniconda3/envs/TensorRT/lib/python3.7/site-packages/trtpy/__main__.py", line 429, in do_templ_list
    url = downloader.process_url_with_key(url)
  File "/root/miniconda3/envs/TensorRT/lib/python3.7/site-packages/trtpy/downloader.py", line 30, in process_url_with_key
    raise RuntimeError(f"Can not get real name from key[{key}], please reconfigure auth key.")
RuntimeError: Can not get real name from key[sxaivip
], please reconfigure auth key.

**Comment by shouxieai** [comment]
我们设置了临时的key，你可以执行trtpy set-key sxaitestkk

**Comment by shouxieai** [comment]
主要原因是提供的免费服务但是奈何流量太大，一次拉取需要支付7毛钱流量费，不得已设置权限。
对于购买课程的人免费提供。

**Comment by shouxieai** [comment]
购买课程的可以在群里查看公告，有公布最新的key

**Comment by shouxieai** [comment]
https://ke.qq.com/course/4993141
这是腾讯课堂的课程链接，仅供参考

**Comment by QIANXUNZDL123** [comment]
> 我们设置了临时的key，你可以执行trtpy set-key sxaitestkk 这个key是临时的，会常常更新，你可以试试

好的  已经加入群里了
