### ISSUE TITLE
win10 pytrt安装有问题

### ISSUE THREAD

**Issue by hanyong-max** [shouxieai/tensorRT_Pro#157]
C:\Users\17243\Desktop\tensorRT_Pro-main\example-python>python test_yolov5.py
Traceback (most recent call last):
  File "C:\Users\17243\Desktop\tensorRT_Pro-main\example-python\test_yolov5.py", line 4, in <module>
    import pytrt as tp
  File "C:\Users\17243\Desktop\tensorRT_Pro-main\example-python\pytrt\__init__.py", line 335, in <module>
    from .libpytrtc import *
ModuleNotFoundError: No module named 'pytrt.libpytrtc'

**Comment by shouxieai** [comment]
这个windows下是不可以的哟，要编译才行

**Comment by SunYiLing123** [comment]
Thanks
