### ISSUE TITLE
error to export

### ISSUE THREAD

**Issue by Allmight0000** [shouxieai/tensorRT_Pro#199]
>python export.py --weights=cf.pt --dynamic --include=onnx --opset=11
export: data=data\coco128.yaml, weights=cf.pt, imgsz=[640, 640], batch_size=1, device=cpu, half=False, inplace=False, train=False, optimize=False, int8=False, dynamic=True, simplify=False, opset=11, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['onnx']
YOLOv5  2021-10-12 torch 1.13.1+cu116 CPU

Traceback (most recent call last):
  File "C:\Users\tjcon\Downloads\yolov5-6.0\export.py", line 364, in <module>
    main(opt)
  File "C:\Users\tjcon\Downloads\yolov5-6.0\export.py", line 359, in main
    run(**vars(opt))
  File "C:\Users\tjcon\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\tjcon\Downloads\yolov5-6.0\export.py", line 277, in run
    model = attempt_load(weights, map_location=device, inplace=True, fuse=True)  # load FP32 model
  File "C:\Users\tjcon\Downloads\yolov5-6.0\models\experimental.py", line 94, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location=map_location)  # load
  File "C:\Users\tjcon\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\tjcon\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 1131, in _load
    result = unpickler.load()
  File "C:\Users\tjcon\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'DetectionModel' on <module 'models.yolo' from 'C:\\Users\\tjcon\\Downloads\\yolov5-6.0\\models\\yolo.py'

**Comment by Allmight0000** [comment]
[2023-08-05 11:52:11][info][trt_builder.cpp:474]:Compile FP16 Onnx Model 'cf.onnx'.
[2023-08-05 11:52:18][warn][trt_builder.cpp:33]:NVInfer: CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
[2023-08-05 11:52:18][error][trt_builder.cpp:30]:NVInfer: C:\Users\tjcon\Downloads\tensorRT_Pro-main\src\tensorRT\onnx_parser\ModelImporter.cpp:736: While parsing node number 221 [Range -> "/model.24/Range_output_0"]:
[2023-08-05 11:52:18][error][trt_builder.cpp:30]:NVInfer: C:\Users\tjcon\Downloads\tensorRT_Pro-main\src\tensorRT\onnx_parser\ModelImporter.cpp:737: --- Begin node ---
[2023-08-05 11:52:18][error][trt_builder.cpp:30]:NVInfer: C:\Users\tjcon\Downloads\tensorRT_Pro-main\src\tensorRT\onnx_parser\ModelImporter.cpp:738: input: "/model.24/Constant_5_output_0"
input: "/model.24/Cast_output_0"
input: "/model.24/Constant_6_output_0"
output: "/model.24/Range_output_0"
name: "/model.24/Range"
op_type: "Range"

[2023-08-05 11:52:18][error][trt_builder.cpp:30]:NVInfer: C:\Users\tjcon\Downloads\tensorRT_Pro-main\src\tensorRT\onnx_parser\ModelImporter.cpp:739: --- End node ---
[2023-08-05 11:52:18][error][trt_builder.cpp:30]:NVInfer: C:\Users\tjcon\Downloads\tensorRT_Pro-main\src\tensorRT\onnx_parser\ModelImporter.cpp:742: ERROR: C:\Users\tjcon\Downloads\tensorRT_Pro-main\src\tensorRT\onnx_parser\builtin_op_importers.cpp:3250 In function importRange:
[8] Assertion failed: inputs.at(0).isInt32() && "For range operator with dynamic inputs, this version of TensorRT only supports INT32!"
[2023-08-05 11:52:18][error][trt_builder.cpp:519]:Can not parse OnnX file: cf.onnx
