### ISSUE TITLE
无法成功运行python/test_yolov5.py

### ISSUE THREAD

**Issue by zjuPeco** [shouxieai/tensorRT_Pro#69]
直接运行报
```
Traceback (most recent call last):
  File "python/test_yolov5.py", line 8, in <module>
    tp.compile_onnx_to_file(1, tp.onnx_hub("yolov5s"), engine_file)
  File "/home/chenquan/.conda/envs/py37/lib/python3.7/site-packages/trtpy/__addition__.py", line 257, in compile_onnx_to_file
    max_workspace_size           = max_workspace_size
TypeError: compileTRT() got an unexpected keyword argument 'output'
```

trtpy的版本是trtpy-1.2.1

用本地的engine_file运行commit出来是None，我看trtpy里
```
class Yolo(object):
    valid : bool
    def __init__(
        self, 
        engine : str, 
        type : YoloType = YoloType.V5, 
        device_id : int = 0, 
        confidence_threshold : float = 0.4,
        nms_threshold : float        = 0.5,
        nms_method    : NMSMethod    = NMSMethod.FastGPU,
        max_objects   : int          = 1024,
        use_multi_preprocess_stream : bool = False
    ): ...
    def commit(self, image : np.ndarray)->SharedFutureObjectBoxArray: ...
```
直接pass了，是不是还没写完，没法用？

感谢解答

**Comment by shouxieai** [comment]
代码里面的python必须编译后使用。这与pip install trtpy的接口不是同一个东西，trtpy的使用请参照readme的介绍
