### ISSUE TITLE
TypeError: compileTRT() got an unexpected keyword argument 'output'

### ISSUE THREAD

**Issue by Nothingzl** [shouxieai/tensorRT_Pro#90]
我输入：python3 test_torch.py
Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /home/zl/.cache/torch/hub/checkpoints/resnet18-5c106cde.pth
100%|███████████████████████████████████████| 44.7M/44.7M [00:48<00:00, 959kB/s]
Traceback (most recent call last):
  File "test_torch.py", line 16, in <module>
    onnx_save_file     = "torch.onnx"
  File "/home/zl/文档/tensorRT_Pro/python/trtpy/__init__.py", line 670, in from_torch
    max_workspace_size           = max_workspace_size
  File "/home/zl/文档/tensorRT_Pro/python/trtpy/__init__.py", line 578, in compile_onnxdata_to_memory
    max_workspace_size           = max_workspace_size
TypeError: compileTRT() got an unexpected keyword argument 'output'

**Comment by shouxieai** [comment]
你需要自行编译trtpy后再执行test_torch.py，不能使用pip install的

**Comment by Nothingzl** [comment]
谢谢大神！
